---
- hosts: all
  become: yes
  tasks:
  - name: Criação de grupos de usuários
    group:
      name: "{{ item }}"
      state: present
    with_items:
    - g_ti
    - g_diretoria
    - g_suporte
  - name: Criação de usuários de suporte
    user:
      name: suporte
      comment: Suporte TI
      groups: g_ti
      append: yes